# Generated by Django 5.2.8 on 2025-11-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music 🎵'), ('conference', 'Conference 🎤'), ('sports', 'Sports 🏆'), ('workshop', 'Workshop 🧪')], default='conference', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
