# Generated by Django 5.2.8 on 2025-11-14 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_add_ticket_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
